FROM java:8

MAINTAINER arun.verma@valvoline.com

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
ENV AM_HOME /opt/forgerock 

#ARG shutdown_port

#ENV CATALINA_OPTS "-XX:MaxRAMPercentage=75.0 -Dcom.iplanet.services.stats.state=off -Djavax.net.ssl.trustStore=/var/run/secrets/truststore/cacerts -Djavax.net.ssl.trustStorePassword=changeit -D"

RUN apt-get install -y curl

RUN ls -l
RUN mkdir openam
WORKDIR $AM_HOME/

ADD AM/tomcat.tar.gz  $AM_HOME/
ADD AM/amster.zip $AM_HOME/

RUN unzip $AM_HOME/amster.zip -d $AM_HOME/amster
#WORKDIR $AM_HOME/amster/


RUN cp -R $AM_HOME/apache-tomcat-9.0.31 $AM_HOME/tomcat
RUN rm -R $AM_HOME/apache-tomcat-9.0.31


RUN rm -fr tomcat/webapps/*
COPY AM/auth.war tomcat/webapps/auth.war
COPY AM/server.xml tomcat/conf/server.xml
COPY AM/run.sh tomcat/run.sh
COPY AM/docker-entrypoint.sh amster/docker-entrypoint.sh

RUN chmod +x tomcat/run.sh
RUN chmod +x amster/docker-entrypoint.sh
COPY AM/pre-install-scripts amster/pre-install-scripts
COPY AM/amster-install.sh amster/amster-install.sh
COPY AM/scripts amster/scripts
COPY AM/post-install-scripts amster/post-install-scripts

#WORKDIR $AM_HOME/amster/scripts
#RUN ls -l

EXPOSE 8180 8143

#CMD ["tomcat/run.sh"]

WORKDIR $AM_HOME/amster/
ENTRYPOINT ["bash", "-x", "docker-entrypoint.sh"]

CMD ["configure"]
